/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Acer
 */
public class AsetMasuk extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    private Statement stat;
    /**
     * Creates new form BarangMasuk
     */
    public AsetMasuk() {
        initComponents();
        bersih();
        kosongkan();
        tampilData();
    }
    
    private void bersih(){
        txtIdBarang.setText(null);
        txtKodeBarang.setText(null);
        txtNamaBarang.setText(null);
        txtTanggalMasuk.setText(null); 
        txtHarga.setText(null);
        txtJumlahBarang.setText(null);
        txtTotalHarga.setText(null);
    }
    
    private void kosongkan(){
        txtIdBarang.setText("");
        txtKodeBarang.setText("");
        txtNamaBarang.setText("");
        txtTanggalMasuk.setText("");
        txtHarga.setText("");
        txtJumlahBarang.setText("");
        txtTotalHarga.setText("");
        txtIdBarang.requestFocus();
        
    }
    
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("Id Barang");
        mod.addColumn("Kode Barang");
        mod.addColumn("Nama Barang");
        mod.addColumn("Tanggal Masuk");
        mod.addColumn("Harga");
        mod.addColumn("Jumlah Barang");
        mod.addColumn("Total Harga");
        tabelAset.setModel(mod);
        Connection conn = koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from aset_masuk";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                   res.getString("id_barang"),
                   res.getString("kode_barang"),
                   res.getString("nama_barang"),
                   res.getString("tanggal_masuk"),
                   res.getString("harga"),
                   res.getString("jumlah_barang"),
                   res.getString("total_harga"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtNamaBarang = new javax.swing.JTextField();
        txtTanggalMasuk = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAset = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtJumlahBarang = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("DATA ASET MASUK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jLabel2.setText("ID BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel3.setText("KODE BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel4.setText("NAMA BARANG");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel5.setText("TANGGAL MASUK");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        txtIdBarang.setText("jTextField1");
        getContentPane().add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 110, -1));

        txtKodeBarang.setText("jTextField2");
        getContentPane().add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 110, -1));

        txtNamaBarang.setText("jTextField3");
        getContentPane().add(txtNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 110, -1));

        txtTanggalMasuk.setText("jTextField4");
        getContentPane().add(txtTanggalMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, -1));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        tabelAset.setBackground(new java.awt.Color(255, 153, 153));
        tabelAset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabelAset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAsetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelAset);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 800, 120));

        jLabel6.setText("HARGA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel7.setText("JUMLAH BARANG");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel8.setText("TOTAL HARGA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        txtHarga.setText("jTextField1");
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 110, -1));

        txtJumlahBarang.setText("jTextField2");
        getContentPane().add(txtJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, -1));

        txtTotalHarga.setText("jTextField3");
        getContentPane().add(txtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, -1));

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into aset_masuk (id_barang, kode_barang, nama_barang, tanggal_masuk, harga, jumlah_barang, total_harga) value (?,?,?,?,?,?,?)");
            stmt.setString(1, txtIdBarang.getText());
            stmt.setString(2, txtKodeBarang.getText());
            stmt.setString(3, txtNamaBarang.getText());
            stmt.setString(4, txtTanggalMasuk.getText());
            stmt.setString(5, txtHarga.getText());
            stmt.setString(6, txtJumlahBarang.getText());
            stmt.setString(7, txtTotalHarga.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
          String sql="UPDATE  aset_masuk SET kode_barang = '"+txtKodeBarang.getText()+"', nama_barang = '"+txtNamaBarang.getText()+"',tanggal_masuk = '"+txtTanggalMasuk.getText()+"',harga = '"+txtHarga.getText()+"',jumlah_barang = '"+txtJumlahBarang.getText()+"',total_harga = '"+txtTotalHarga.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "data berhasil di edit");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Edit gagal"+e.getMessage());
        }
        tampilData();
        kosongkan();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelAsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAsetMouseClicked
        // TODO add your handling code here:
        int i = tabelAset.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tabelAset.getValueAt(i, 0);
        String code1 = (String)tabelAset.getValueAt(i, 1);
        String code2 = (String)tabelAset.getValueAt(i, 2);
        String code3 = (String)tabelAset.getValueAt(i, 3);
        String code4 = (String)tabelAset.getValueAt(i, 4);
        String code5 = (String)tabelAset.getValueAt(i, 5);
        String code6 = (String)tabelAset.getValueAt(i, 6);
        txtIdBarang.setText(code);
        txtKodeBarang.setText(code1);
        txtNamaBarang.setText(code2);
        txtTanggalMasuk.setText(code3);
        txtHarga.setText(code4);
        txtJumlahBarang.setText(code5);
        txtTotalHarga.setText(code6);
    }//GEN-LAST:event_tabelAsetMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
          String sql="delete from aset_masuk where id_barang='"+txtIdBarang.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(this, "Berhasil dihapus");
          
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try{
          String sql="INSERT INTO aset_masuk VALUES ('"+txtIdBarang.getText()+"','"+txtKodeBarang.getText()+"','"+txtNamaBarang.getText()+"','"+txtTanggalMasuk.getText()+"','"+txtHarga.getText()+"','"+txtJumlahBarang.getText()+"','"+txtTotalHarga.getText()+"')";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Tambah data berhasil");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData(); 
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/projekAkhir/laporanasetmasuk.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsetMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsetMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsetMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsetMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsetMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelAset;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtTanggalMasuk;
    private javax.swing.JTextField txtTotalHarga;
    // End of variables declaration//GEN-END:variables
}
