/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Acer
 */
public class Barang extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    private Statement stat;
    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        bersih();
        tampilData();
        kosongkan();
        setLocationRelativeTo(this);
    }
    
    private void bersih(){
        txtIdBarang.setText(null);
        txtKodeBarang.setText(null);
        txtLuas.setText(null);
        txtHarga.setText(null);
        txtHakMilik.setText(null);
        txtTempat.setText(null);
        
    }
    
    private void kosongkan(){
        txtIdBarang.setText("");
        txtKodeBarang.setText("");
        txtLuas.setText("");
        txtHarga.setText("");
        txtHakMilik.setText("");
        txtTempat.setText("");
        txtIdBarang.requestFocus();
        
    }
    
  
    
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("Id Barang");
        mod.addColumn("Kode Barang");
        mod.addColumn("Luas");
        mod.addColumn("Harga");
        mod.addColumn("Hak Milik");
        mod.addColumn("Tempat");
        tabelBarang.setModel(mod);
        Connection conn = koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from data_barang";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                   res.getString("id_barang"),
                   res.getString("kode_barang"),
                   res.getString("luas"),
                   res.getString("harga"),
                   res.getString("hak_milik"),
                   res.getString("tempat")
                });
            }
        }catch (SQLException e){
            System.out.println(e);
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        txtKodeBarang = new javax.swing.JTextField();
        txtLuas = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtHakMilik = new javax.swing.JTextField();
        txtTempat = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setText("ID BARANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLabel3.setText("KODE BARANG");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel4.setText("LUAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel5.setText("HARGA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel6.setText("HAK MILIK");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel7.setText("TEMPAT");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        txtIdBarang.setText("jTextField1");
        getContentPane().add(txtIdBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 110, -1));

        txtKodeBarang.setText("jTextField2");
        getContentPane().add(txtKodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 110, -1));

        txtLuas.setText("jTextField3");
        getContentPane().add(txtLuas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 110, -1));

        txtHarga.setText("jTextField4");
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 110, -1));

        txtHakMilik.setText("jTextField5");
        getContentPane().add(txtHakMilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, -1));

        txtTempat.setText("jTextField6");
        getContentPane().add(txtTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 110, -1));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        tabelBarang.setBackground(new java.awt.Color(255, 153, 153));
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 560, 130));

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into data_barang (id_barang, kode_barang, luas, harga, hak_milik, tempat) value (?,?,?,?,?,?)");
            stmt.setString(1, txtIdBarang.getText());
            stmt.setString(2, txtKodeBarang.getText());
            stmt.setString(3, txtLuas.getText());
            stmt.setString(4, txtHarga.getText());
            stmt.setString(5, txtHakMilik.getText());
            stmt.setString(6, txtTempat.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
          String sql="UPDATE  data_barang SET kode_barang = '"+txtKodeBarang.getText()+"', luas = '"+txtLuas.getText()+"',harga = '"+txtHarga.getText()+"',hak_milik = '"+txtHakMilik.getText()+"',tempat = '"+txtTempat.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "data berhasil di edit");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Edit gagal"+e.getMessage());
        }
        tampilData();
        kosongkan();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
        // TODO add your handling code here:
        int i = tabelBarang.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tabelBarang.getValueAt(i, 0);
        String code1 = (String)tabelBarang.getValueAt(i, 1);
        String code2 = (String)tabelBarang.getValueAt(i, 2);
        String code3 = (String)tabelBarang.getValueAt(i, 3);
        String code4 = (String)tabelBarang.getValueAt(i, 4);
        String code5 = (String)tabelBarang.getValueAt(i, 5);
        txtIdBarang.setText(code);
        txtKodeBarang.setText(code1);
        txtLuas.setText(code2);
        txtHarga.setText(code3);
        txtHakMilik.setText(code4);
        txtTempat.setText(code5);
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
          String sql="delete from data_barang where id_barang='"+txtIdBarang.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(this, "Berhasil dihapus");
          
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
       
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
       try{
          String sql="INSERT INTO data_barang VALUES ('"+txtIdBarang.getText()+"','"+txtKodeBarang.getText()+"','"+txtLuas.getText()+"','"+txtHarga.getText()+"','"+txtHakMilik.getText()+"','"+txtTempat.getText()+"')";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Tambah data berhasil");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData(); 
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/projekAkhir/laporanbarang.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTextField txtHakMilik;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtLuas;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}
