/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekakhir;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Acer
 */
public class Pns extends javax.swing.JFrame {
    DefaultTableModel mod;
    private String SQL;
    private Statement stat;
    /**
     * Creates new form Supplier
     */
    public Pns() {
        initComponents();
        bersih();
        kosongkan();
        tampilData();
        setLocationRelativeTo(this);
    }
    
    private void bersih(){
        txtNip.setText(null);
        txtNama.setText(null);
        txtTempatLahir.setText(null);
        txtJabatan.setText(null);
        txtGolongan.setText(null);
        txtPendidikan.setText(null);
        
    }
    
    private void kosongkan(){
        txtNip.setText("");
        txtNama.setText("");
        txtTempatLahir.setText("");
        txtJabatan.setText("");
        txtGolongan.setText("");
        txtPendidikan.setText(null);
        txtNip.requestFocus();
        
    }
    
    private void tampilData(){
        mod = new DefaultTableModel();
        mod.addColumn("NIP");
        mod.addColumn("Nama");
        mod.addColumn("Tempat Lahir");
        mod.addColumn("Jabatan");
        mod.addColumn("Golongan");
        mod.addColumn("Pendidikan Terakhir");
        tabelPns.setModel(mod);
        Connection conn = koneksi.getConnection();
        try{
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from data_pns";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while(res.next()){
                mod.addRow(new Object[]{
                   res.getString("nip"),
                   res.getString("nama"),
                   res.getString("tempat_lahir"),
                   res.getString("jabatan"),
                   res.getString("golongan"),
                   res.getString("pendidikan_terakhir"),
                });
            }
        }catch (SQLException e){
            System.out.println(e);
            
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        txtJabatan = new javax.swing.JTextField();
        txtGolongan = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPns = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtPendidikan = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA PNS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jLabel2.setText("NIP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 46, -1, -1));

        jLabel3.setText("NAMA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 77, -1, -1));

        jLabel4.setText("TEMPAT LAHIR");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 108, -1, -1));

        jLabel5.setText("JABATAN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 139, -1, -1));

        jLabel6.setText("GOLONGAN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 170, -1, -1));

        txtNip.setText("jTextField1");
        getContentPane().add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 43, 116, -1));

        txtNama.setText("jTextField2");
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 74, 116, -1));

        txtTempatLahir.setText("jTextField3");
        getContentPane().add(txtTempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 105, 116, -1));

        txtJabatan.setText("jTextField4");
        getContentPane().add(txtJabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 136, 116, -1));

        txtGolongan.setText("jTextField5");
        getContentPane().add(txtGolongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 167, 116, -1));

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        tabelPns.setBackground(new java.awt.Color(255, 153, 153));
        tabelPns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tabelPns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPnsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPns);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 610, 130));

        jLabel7.setText("PENDIDIKAN TERAKHIR");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        txtPendidikan.setText("jTextField1");
        getContentPane().add(txtPendidikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 120, -1));

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement
        ("insert into data_pns (nip, nama, tempat_lahir, jabatan, golongan, pendidikan_terakhir) value (?,?,?,?,?,?)");
            stmt.setString(1, txtNip.getText());
            stmt.setString(2, txtNama.getText());
            stmt.setString(3, txtTempatLahir.getText());
            stmt.setString(4, txtJabatan.getText());
            stmt.setString(5, txtGolongan.getText());
            stmt.setString(6, txtPendidikan.getText());
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            tampilData();
            bersih();
        }catch (SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        try{
          String sql="UPDATE  data_pns SET nama = '"+txtNama.getText()+"', tempat_lahir = '"+txtTempatLahir.getText()+"',jabatan = '"+txtJabatan.getText()+"',golongan = '"+txtGolongan.getText()+"',pendidikan_terakhir = '"+txtPendidikan.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "data berhasil di edit");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Edit gagal"+e.getMessage());
        }
        tampilData();
        kosongkan();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tabelPnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPnsMouseClicked
        // TODO add your handling code here:
        int i = tabelPns.getSelectedRow();
        if(i==-1){
            return;
        }
        String code = (String)tabelPns.getValueAt(i, 0);
        String code1 = (String)tabelPns.getValueAt(i, 1);
        String code2 = (String)tabelPns.getValueAt(i, 2);
        String code3 = (String)tabelPns.getValueAt(i, 3);
        String code4 = (String)tabelPns.getValueAt(i, 4);
        String code5 = (String)tabelPns.getValueAt(i, 5);
        txtNip.setText(code);
        txtNama.setText(code1);
        txtTempatLahir.setText(code2);
        txtJabatan.setText(code3);
        txtGolongan.setText(code4);
        txtPendidikan.setText(code5);
    }//GEN-LAST:event_tabelPnsMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
          String sql="delete from data_pns where nip='"+txtNip.getText()+"'";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(this, "Berhasil dihapus");
          
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try{
          String sql="INSERT INTO data_pns VALUES ('"+txtNip.getText()+"','"+txtNama.getText()+"','"+txtTempatLahir.getText()+"','"+txtJabatan.getText()+"','"+txtGolongan.getText()+"','"+txtPendidikan.getText()+"')";
          java.sql.Connection conn=(Connection)koneksi.getConnection();
          java.sql.PreparedStatement stmt=conn.prepareStatement(sql);
          stmt.execute();
          JOptionPane.showMessageDialog(null, "Tambah data berhasil");
          }catch (SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        bersih();
        tampilData(); 
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            File namafile = new File("src/projekAkhir/laporanpns.jasper");
            JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPns;
    private javax.swing.JTextField txtGolongan;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtPendidikan;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
